### ISSUE TITLE
Error running maven command

### ISSUE THREAD

**Issue by emoran** [estebanwasinger/dataweave-playground#9] opened 2020-02-11 16:04 UTC
Hi Esteban,

I'm trying to run your project, when I run the _mvn exec:java -Dexec.mainClass="com.github.estebanwasinger.DWPlayground"_ command I see this error:

Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project weave-playground: An exception occured while executing the Java class. com.github.estebanwasinger.DWPlayground 

Do I missed something?

Best regards!

**Comment by bpsligro** [comment] 2020-02-16 18:32
Same question as I have.
NO any response. 👎

**Comment by troyhofeling** [comment] 2020-02-17 20:59
Please support or remove from public view. Seems all the issues are related and a little support would go a long way. I realize this is not an "official" Mulesoft tool, but, given the terrible DW tools provided in Studio, a "supported" tool like this goes a long way to restore confidence for your dev community.

**Comment by emoran** [comment] 2020-02-17 21:36
Hi @bpsligro @troyhofeling 

A quick fix I did is to use IntelliJ IDEA CE to import the project as **maven** seems it automatically imported all dependencies. Open the  DWPlayground class and clic the green play "run"icon. The application showed up. 

![image](https://user-images.githubusercontent.com/1028534/74687820-84ef0f00-51a3-11ea-9604-95ef6bc355d6.png)


![image](https://user-images.githubusercontent.com/1028534/74687528-a69bc680-51a2-11ea-9c1f-8789c70955e8.png)

Still I'm trying to get the maven command we can use, for now I guess it might help.

Best!

**Comment by troyhofeling** [comment] 2020-02-17 23:13
Thank you @emoran - it was a bit trickier for me but I did get it working in IntelliJ.

**Comment by bpsligro** [comment] 2020-02-18 17:40
Thanks @emoran,
I have it also working but with a big work around, I build the Java project first in Eclipse 2019-12 JEE. And then I run it in Eclipse one, which succeeds. Then the CMD line params which are generated in Eclipse are copied to a batch file and then it works.
Thanks for your support, have a nice evening.
And off course I am interested when you find a solution for running it with  mvn  exec.
Kind regards.

**Comment by DominikNagy** [comment] 2020-07-04 21:36
If anyone has problems running this with openjdk, just add a javafx maven dependency. The issue is that openjdk doesn't come with javafx. 


        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>14.0.1</version>
        </dependency>

**Comment by tools400** [comment] 2020-09-01 05:36
Emoran,

Stupid question, but did you run "mvn clean compile" before "mvn:exec..."? That and using Java 11 fixed my problems when attempting to run the project.

> Hi Esteban,
> 
> I'm trying to run your project, when I run the _mvn exec:java -Dexec.mainClass="com.github.estebanwasinger.DWPlayground"_ command I see this error:
> 
> Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project weave-playground: An exception occured while executing the Java class. com.github.estebanwasinger.DWPlayground
> 
> Do I missed something?
> 
> Best regards!

**Comment by estebanwasinger** [comment] 2020-09-08 20:31
Hi all,

Thanks for raising the issues, and sorry for not being so active, this is a side project that I have I don't invest too much time on this.

As @tools400 I upgraded the Playground to use latest DW version and also make it compatible with Java 11.

In addition to that I uploaded an executable Jar in the Release section.

Thanks
Esteban

**Comment by bpsligro** [comment] 2020-09-09 10:37
Hi Esteban,
At first thank you very much for your effort, I have tested it on Java 8 and 11.08 (AdoptopenJDK)  and it works like a charm.
I have noticed in the POM.xml file you have added the mule 4.3 and dataweave 2.3 support, that is just great.
Kind regards

**Comment by estebanwasinger** [comment] 2020-09-16 23:15
You are welcome, I will proceed to close this issue.
Thanks everyone!

**Closed as completed** 2020-09-16 23:15 UTC
